# Generated by Django 5.2.12 on 2026-04-05 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0004_productfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeedback',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
